---
apiVersion: v1
kind: Service
metadata:
  name: nginx-argo-test-service
  namespace: argo-test
spec:
  selector:
    app: nginx
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
